# Generated by Django 3.1.6 on 2021-02-07 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerPlant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PowerPlantInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_timestamp', models.DateTimeField()),
                ('actual', models.IntegerField()),
                ('installed', models.IntegerField()),
                ('powerplant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.powerplant')),
            ],
        ),
    ]
